# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: demo1_database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: hieu123

